[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
kenzu = "0.1.1"
nekoprint = "0.1.3"
nekotracing = "0.0.5"
regex = "1.12.2"
shori = "0.1.2"
uuid = "1.18.1"
